date.timezone = America/Montreal
display_errors = Off
error_reporting = E_ALL
upload_max_filesize = 64M
post_max_size = 70M
memory_limit = 256M
opcache.enable = 1
opcache.memory_consumption = 128
opcache.validate_timestamps = 1
