/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as PingRouteImport } from './routes/ping'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NavigationDatabaseIdRouteImport } from './routes/navigation.$databaseId'
import { Route as TablesDatabaseIdTableIdRouteImport } from './routes/tables.$databaseId.$tableId'
import { Route as BuilderDatabaseIdTableIdRouteImport } from './routes/builder.$databaseId.$tableId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationDatabaseIdRoute = NavigationDatabaseIdRouteImport.update({
  id: '/navigation/$databaseId',
  path: '/navigation/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesDatabaseIdTableIdRoute = TablesDatabaseIdTableIdRouteImport.update({
  id: '/tables/$databaseId/$tableId',
  path: '/tables/$databaseId/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderDatabaseIdTableIdRoute =
  BuilderDatabaseIdTableIdRouteImport.update({
    id: '/builder/$databaseId/$tableId',
    path: '/builder/$databaseId/$tableId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/ping': typeof PingRoute
  '/workspaces': typeof WorkspacesRoute
  '/navigation/$databaseId': typeof NavigationDatabaseIdRoute
  '/builder/$databaseId/$tableId': typeof BuilderDatabaseIdTableIdRoute
  '/tables/$databaseId/$tableId': typeof TablesDatabaseIdTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/ping': typeof PingRoute
  '/workspaces': typeof WorkspacesRoute
  '/navigation/$databaseId': typeof NavigationDatabaseIdRoute
  '/builder/$databaseId/$tableId': typeof BuilderDatabaseIdTableIdRoute
  '/tables/$databaseId/$tableId': typeof TablesDatabaseIdTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/ping': typeof PingRoute
  '/workspaces': typeof WorkspacesRoute
  '/navigation/$databaseId': typeof NavigationDatabaseIdRoute
  '/builder/$databaseId/$tableId': typeof BuilderDatabaseIdTableIdRoute
  '/tables/$databaseId/$tableId': typeof TablesDatabaseIdTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not-found'
    | '/ping'
    | '/workspaces'
    | '/navigation/$databaseId'
    | '/builder/$databaseId/$tableId'
    | '/tables/$databaseId/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/not-found'
    | '/ping'
    | '/workspaces'
    | '/navigation/$databaseId'
    | '/builder/$databaseId/$tableId'
    | '/tables/$databaseId/$tableId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/not-found'
    | '/ping'
    | '/workspaces'
    | '/navigation/$databaseId'
    | '/builder/$databaseId/$tableId'
    | '/tables/$databaseId/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  PingRoute: typeof PingRoute
  WorkspacesRoute: typeof WorkspacesRoute
  NavigationDatabaseIdRoute: typeof NavigationDatabaseIdRoute
  BuilderDatabaseIdTableIdRoute: typeof BuilderDatabaseIdTableIdRoute
  TablesDatabaseIdTableIdRoute: typeof TablesDatabaseIdTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation/$databaseId': {
      id: '/navigation/$databaseId'
      path: '/navigation/$databaseId'
      fullPath: '/navigation/$databaseId'
      preLoaderRoute: typeof NavigationDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$databaseId/$tableId': {
      id: '/tables/$databaseId/$tableId'
      path: '/tables/$databaseId/$tableId'
      fullPath: '/tables/$databaseId/$tableId'
      preLoaderRoute: typeof TablesDatabaseIdTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$databaseId/$tableId': {
      id: '/builder/$databaseId/$tableId'
      path: '/builder/$databaseId/$tableId'
      fullPath: '/builder/$databaseId/$tableId'
      preLoaderRoute: typeof BuilderDatabaseIdTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  PingRoute: PingRoute,
  WorkspacesRoute: WorkspacesRoute,
  NavigationDatabaseIdRoute: NavigationDatabaseIdRoute,
  BuilderDatabaseIdTableIdRoute: BuilderDatabaseIdTableIdRoute,
  TablesDatabaseIdTableIdRoute: TablesDatabaseIdTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
